### ISSUE TITLE
Why is "Tricube" missing in LocalPolynomialFilterFactory

### ISSUE THREAD

**Issue by ChristianeHofer** [jdemetra/jdplus-experimental#38]
In jdplus.experimentalsa.base.core.filters.LocalPolynomialFilterFactory in kernel "TriCube" is missing. Is it just missing, or are there open methodology questions that have to be solved?

**Comment by palatej** [comment]
I just forgot it. It has been added (in LocalPolynomialFilters, which is now in the main project)
